print("Arrays")
print("init as [1, 2, 5, 7, 3, 4]")
arr = [1, 2, 5, 7, 3, 4]

arr.append(8)
print("CREATE 8")
print(arr)
print("CREATE from another list [-1, -2]")
arr += [-1, -2]
print(arr)

print("READ at index 3")
print(arr[3])
print("READ at index -2")
print(arr[-2])
print("READ by slice arr[:2]")
print(arr[:2])

print("UPDATE last element to 9")
arr[len(arr)-1] = 9
print(arr)

print("DELETE by value = 3")
arr.remove(3)
print(arr)
print("DELETE by index = 3")
arr.pop(3)
print(arr)

print("Other methods:")
print(".append(11)")
arr.append(11)
print(arr)
print(".extend([22, 33])")
arr.extend([22, 33])
print(arr)
print(".insert(1, 11)")
arr.insert(1, 11)
print(arr)
print(".index(5)")
print(arr.index(5))
print(".count(11)")
print(arr.count(11))
print(".sort()")
arr.sort()
print(arr)
print(".reverse()")
arr.reverse()
print(arr)
print(".clear()")
arr.clear()
print(arr)