FROM python:3.6.2

# update installation
RUN apt-get -y update
RUN apt-get -y upgrade

# create directories and copy files
RUN mkdir -p /mnt/app
ADD . /mnt/app
WORKDIR /mnt/app

# install dependencies and app
RUN pip install -r requirements.txt

# Run the image as a non-root user
RUN useradd -m myuser
USER myuser

CMD GUNICORN_CMD_ARGS="--bind=0.0.0.0:$PORT  --chdir /mnt/app/ml_app" gunicorn wsgi
